// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7sPnwGHNT1Gzv7wCSBz5YTxozqO2Lz-0',
    appId: '1:1086983595543:web:c08213cebf76b3efd21e52',
    messagingSenderId: '1086983595543',
    projectId: 'alura-crashlytics-18e5a',
    authDomain: 'alura-crashlytics-18e5a.firebaseapp.com',
    storageBucket: 'alura-crashlytics-18e5a.appspot.com',
    measurementId: 'G-QT0R86MGSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRTwQjSJ3B1aLrHZr5DSuefCfH0NcxwAQ',
    appId: '1:1086983595543:android:91440f9ba33353d7d21e52',
    messagingSenderId: '1086983595543',
    projectId: 'alura-crashlytics-18e5a',
    storageBucket: 'alura-crashlytics-18e5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq1DCg7xSSf_xDTj0qhSJ94HbRcdHjw5k',
    appId: '1:1086983595543:ios:c007c4f854ccd07bd21e52',
    messagingSenderId: '1086983595543',
    projectId: 'alura-crashlytics-18e5a',
    storageBucket: 'alura-crashlytics-18e5a.appspot.com',
    iosClientId: '1086983595543-cm23ma6iqvo4fiko71qgol1bsepp3vm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bytebank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq1DCg7xSSf_xDTj0qhSJ94HbRcdHjw5k',
    appId: '1:1086983595543:ios:c007c4f854ccd07bd21e52',
    messagingSenderId: '1086983595543',
    projectId: 'alura-crashlytics-18e5a',
    storageBucket: 'alura-crashlytics-18e5a.appspot.com',
    iosClientId: '1086983595543-cm23ma6iqvo4fiko71qgol1bsepp3vm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bytebank',
  );
}
